services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres  # Kita gunakan DB default dulu
    ports:
      - '5432:5432'
    networks:
      - keploy-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - keploy-network
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=postgres

networks:
  keploy-network:
    driver: bridge
